### ISSUE TITLE
Component breaks when not Remote Debugging in React Native

### ISSUE THREAD

**Issue by clarksandholtz** [HandlebarLabs/code-and-coffee#5] opened 2018-01-17 17:13 UTC
## Question Description

I have noticed in a React Native app that I am building that some things will work when I am debugging the JS remotely, but they don't work when I am not.

This behavior seems to show up around code where I am mapping over an array and returning JSX. There are plenty of places where I am able to do so, but some places where it breaks.

I believe this is due to the fact that while remote debugging, the JS is being processed by Chrome's V8 engine, where on device it is being processed by the JavaScript Core engine that Safari uses. See this [link](https://facebook.github.io/react-native/docs/javascript-environment.html) for details.

## How can I get started?

The following code works while debugging remotely, but freezes up the app when not:

```
import React from 'react'
import { ScreenContainer, BackButton, PurpleButton } from '../elements'
import glamorous from 'glamorous-native'
import PropTypes from 'prop-types'
import serverProxy from '../../server-proxy'
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'
import theme from '../../theme'
import { parse, format, asYouType } from 'libphonenumber-js'
import { TouchableOpacity, Text } from 'react-native'
import { Actions } from 'react-native-router-flux'

export default class VerifyPhoneScreen extends React.Component {
  static propTypes = {
    onVerified: PropTypes.func.isRequired,
  }

  constructor(props) {
    super(props)
    this.verificationInputs = []
    this.state = {
      countryCode: '1',
      phoneNumber: '',
      validNumber: false,
      sendingText: false,
      phoneNumberSubmitted: false,
      verificationCode: ['', '', '', '', '', ''],
    }

  }

    verificationCodeTextChange = (index, text) => {
        if (!text) {
          return;
        }
        let verificationCode = this.state.verificationCode;
        verificationCode[index] = text;
        this.setState({ verificationCode });
        if (index < verificationCode.length - 1) {
          this.verificationInputs[index + 1].focus();
        }
      };

	.
	.
	.
	
  renderVerificationInputs = () => {
    this.verificationInputs = []
    const inputs = this.state.verificationCode.map((item, index) => {
      return (
        <LightGrayInputBox
          innerRef={ref => {
            this.verificationInputs[index] = ref
          }}
          onFocus={() => {
            let verificationCode = this.state.verificationCode
            verificationCode[index] = ''
            this.setState(verificationCode)
          }}
          maxLength={1}
          key={index}
          value={this.state.verificationCode[index]}
          onChangeText={text => this.verificationCodeTextChange(index, text)}
          underlineColorAndroid="rgba(0,0,0,0)"
          keyboardType="phone-pad"
        />
      )
    })
    return inputs
  }
  
	.
	.
	.

  render() {
    return (
      <KeyboardAwareScrollView
        contentContainerStyle={{
          display: 'flex',
          flex: 1,
          justifyContent: 'center',
        }}
        keyboardShouldPersistTaps="handled"
      >
        <BackButton pop={Actions.currentScene !== '_register'} goto="launch" />
        {this.state.phoneNumberSubmitted ? (
          <VerificationWrapper>
            <PurpleText marginBottom={20}>Enter your code</PurpleText>
            <TouchableOpacity onPress={this.editPhoneNumber}>
              <PurpleText marginBottom={40}>{this.formatNumber()}</PurpleText>
            </TouchableOpacity>
            <VerificationCodeInputsContainer>
              {this.renderVerificationInputs()}
            </VerificationCodeInputsContainer>
            <PurpleButton
              onPress={this.checkVerificationCode}
              disabled={
                !this.state.verificationCode.every(
                  value => (value ? true : false),
                )
              }
              title="submit"
            />
            <TouchableOpacity onPress={this.resendCode}>
              <PurpleText paddingTop={20}>Didn't get a code?</PurpleText>
            </TouchableOpacity>
          </VerificationWrapper>
        ) : (
          <VerificationWrapper>
            <PurpleText>Enter your mobile number</PurpleText>
            <PhoneInputContainer>
              <PhoneInput
                width="20%"
                value={'+ ' + this.state.countryCode}
                underlineColorAndroid="rgba(0,0,0,0)"
                keyboardType="phone-pad"
                onChangeText={this.onChangeCountryCode}
                maxLength={3}
              />
              <PhoneInput
                width="75%"
                autoFocus
                underlineColorAndroid="rgba(0,0,0,0)"
                keyboardType="phone-pad"
                value={this.state.phoneNumber}
                onChangeText={this.onChangePhoneNumber}
                maxLength={10}
              />
            </PhoneInputContainer>
            <PurpleButton
              onPress={this.submitNumber}
              disabled={!this.state.validNumber}
              title="submit"
            />
          </VerificationWrapper>
        )}
      </KeyboardAwareScrollView>
    )
  }
}

	.
	.
	.
``` 

Testing things in the Safari console can help identify things that do and don't work in the Javascript Core engine.

**Comment by spencercarli** [comment] 2018-01-24 19:00
Hey @clarksandholtz thanks for posting this! I just tried to reproduce this issue (code posted below) but am unable to. Could you try and put together a piece of code that demonstrates this?

I tried to pull from insights in your example but I think there's something about your `LightGrayInputBox` that's causing the issue.

My test code:
```javascript
import React from 'react';
import { SafeAreaView, View, StyleSheet, TextInput, Button } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  block: {
    backgroundColor: 'red',
    height: 30,
    width: '100%',
    marginBottom: 15,
  },
});

class App extends React.Component {
  constructor() {
    super();

    this.references = [];
    this.state = {
      verificationCode: ['', '', '', '', '', ''],
    }
  }

  renderArrayOfJSX = () => {
    return this.state.verificationCode.map((item, index) => {
      return <TextInput
        ref={ref => this.references[index] = ref}
        style={styles.block}
        key={index}
      />;
    });
  }

  render() {
    return (
      <SafeAreaView style={styles.container}>
        {this.renderArrayOfJSX()}
        <Button
          title="focus on first input"
          onPress={() => this.references[0].focus()}
        />
      </SafeAreaView>
    );
  }
}

export default App;
```

**Comment by spencercarli** [comment] 2018-02-07 17:05
Going to close this since I can't reproduce the issue.

**Closed as completed by spencercarli** 2018-02-07 17:05 UTC
Labels: react native
